### ISSUE TITLE
introduce "migrating from redis" page

### ISSUE THREAD

**Issue by romange** [dragonflydb/documentation#100]
Overlaps with #88 but is a bit differrent.
Based on many discussions, people are having trouble migrating their rdb files to Dragonfly. 
We should provide a document (possibly blog post as well) on how to load the data from redis (caveats, limitations)
including which flags to pass so that DF will load rdb but will save dfs format. How to enforce saving the rdb, or dfs 
(SAVE DF/SAVE RDB). Mention we do not support redis 7 rdb format (subject to issue https://github.com/dragonflydb/dragonfly/issues/1403 ) etc.

**Comment by Niennienzz** [comment]
I think the original migration section PR (https://github.com/dragonflydb/documentation/pull/128) has covered this issue.

Added a new issue (https://github.com/dragonflydb/documentation/issues/163) to finish the "Migrating Redis Cluster to Dragonfly Single Node" part.
