### ISSUE TITLE
need docs for running in memcached mode

### ISSUE THREAD

**Issue by romange** [dragonflydb/documentation#55]

**Comment by Niennienzz** [comment]
Made a PR to fix the flag name.

Please let me know if there's anything else I need to add.
- For instance, I wonder if Memcached is enabled, does Dragonfly disable the Redis API automatically?

**Comment by romange** [comment]
no, we have both ports and you can actually use both redis and Memcached APIs simultaneously

**Comment by Niennienzz** [comment]
Thanks Roman. I fixed the flag name, and added a section about keyspace sharing in the doc.

Please see details in the PR https://github.com/dragonflydb/documentation/pull/144
