### ISSUE TITLE
need a section explaining on how to migrate from redis to df

### ISSUE THREAD

**Issue by romange** [dragonflydb/documentation#58]

**Comment by Niennienzz** [comment]
Currently #58, #88 and #100 are partially already covered by the following:
- https://www.dragonflydb.io/docs/managing-dragonfly/backups
- https://www.dragonflydb.io/docs/migrating-to-dragonfly

I will walk through the doc again making sure issues are 100% covered as desired.

**Comment by Niennienzz** [comment]
I think the original migration section PR (https://github.com/dragonflydb/documentation/pull/128) has covered this issue.

Added a new issue (https://github.com/dragonflydb/documentation/issues/163) to finish the "Migrating Redis Cluster to Dragonfly Single Node" part.
