### ISSUE TITLE
Is replication to replicas synchronous?

### ISSUE THREAD

**Issue by dreusel** [dragonflydb/documentation#69]
For me the main concern/limitation about using Redis is it's asynchronous replication to replicas and the consistency issues following from it. My primary consideration for using an alternative would be if it solved this issue. However even though this issue is described on the website as one of the 5 primary reasons for Redis to fail, I can't find any concrete information on dragonfly's website or documentation as to whether it solves this issue, other than 'it handle so much more load on a single machine that you won't need clustering'. Which is a non-answer for any application where availability is of concern.

**Comment by dranikpg** [comment]
Hi! 

Currently Dragonfly replication is fully asynchronous and works similar to Redis. Fully synchronous replication greatly reduces throughput and as such Redis/Dragonfly use cases (there are lots of consistent data stores as well), so its not a primary goal in the nearest future.

Please use our main repo or discord channel (link on readme) for further questions - its what we check daily
