### ISSUE TITLE
add kubernetes operator to K8s docs

### ISSUE THREAD

**Issue by worldsoup** [dragonflydb/documentation#74]
@Pothulapati @ashotland can one of you please update the getting started with K8s page to include instructions for the operator?

**Comment by worldsoup** [comment]
also related question...is Docker the most appropriate installtion method for K8s operators? I looked at some others and seems installing operators via helm or downloading and installing via CTL is more common:
https://docs.couchbase.com/operator/current/install-kubernetes.html
https://docs.redis.com/latest/kubernetes/deployment/quick-start/
https://www.mongodb.com/try/download/community

**Comment by Pothulapati** [comment]
@worldsoup Its still docker at the end of the day even for the links you mentioned. The installation can vary i.e helm, their own binary, etc but at the end of the day its the operator docker image that runs in Kubernetes.

Currently, The operator installation with dragonfly is the raw manifests that user will install. We didn't find the need for a Helm package on the Operator yet (probably won't in the near future too).
