### ISSUE TITLE
Add examples to snapshotting document

### ISSUE THREAD

**Issue by royjacobson** [dragonflydb/documentation#88]
for example, how to load a dump.rdb from redis into dragonfly

**Comment by Niennienzz** [comment]
Currently #58, #88 and #100 are partially already covered by the following:
- https://www.dragonflydb.io/docs/managing-dragonfly/backups
- https://www.dragonflydb.io/docs/migrating-to-dragonfly

I will walk through the doc again making sure issues are 100% covered as desired.

**Comment by romange** [comment]
Thank you @Niennienzz !

**Comment by romange** [comment]
Closing as completed
