### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by uhthomas** [dragonflydb/documentation#89]
Hey!

I'm running Chromium on Arch Linux and the performance of the documentation site can be slow. I assume this is because of weirdness with hardware acceleration and chromium on Linux. That said, most other sites work fine.

I hope this doesn't come off as critical or mean, I think Dragonfly is great. I wanted to raise this in case you were unaware.

![image](https://github.com/dragonflydb/documentation/assets/9749173/d0da0d86-51e4-44f4-bff3-65fc9cc4e998)

**Comment by vahnag** [comment]
Hey, @uhthomas! I'm the developer of the documentation website.

I'm on Mac and did not see any performance issues on Chrome. It would take me lots of effort to get started with Linux now to test it. 

I suppose the issue might be with SVG gradients used in backgrounds. I created a preview deployment with those removed. Can you please help me debug this by testing the preview deployment and letting me know if it fixes your issues?

https://documentation-git-no-svg-gradients-test-dragonfly-db.vercel.app/

Thank you.

**Comment by uhthomas** [comment]
>I'm on Mac and did not see any performance issues on Chrome.

I'm not surprised. Both macOS and Windows should have good hardware acceleration.

The preview deployment is way better.

![image](https://github.com/dragonflydb/documentation/assets/9749173/4c0fff22-6c22-43cc-8e14-7566fe60bbab)
