### ISSUE TITLE
Bit operations family not documented

### ISSUE THREAD

**Issue by chakaz** [dragonflydb/documentation#95]
Unless I'm missing something, or that it's a weird place, I couldn't find the documentation for any of the bit operations:

https://www.dragonflydb.io/docs/category/command-reference

**Comment by romange** [comment]
it's in strings because they are technically strings.

**Comment by chakaz** [comment]
Oh right, I see!
fwiw, in Redis they are documented in a separate "group" named Bitmap. I can move it if you think it's better, or keep as is. Your call.

**Comment by romange** [comment]
It's fine where they are at this point.
